/**
 * tlc-sl/src/targets/js.mjs
 * JavaScript enforcement target.
 *
 * Emits a self-describing ES module that embeds the compiled model and decides
 * via the shared interpreter (interp.decide). The runtime check and the model
 * checker therefore share one evaluator and cannot drift. The canonical compiled
 * artifact is the embedded model JSON; this module is its executable wrapper.
 */

export function emitJS(model) {
  const json = JSON.stringify(model, null, 2);
  return `// GENERATED by the TLC-SL compiler — do not edit by hand.
// Invariant: ${model.id} — ${model.title}
// Article: ${model.article}   Enforcement: ${model.level}
//
// This module embeds the compiled model and evaluates actions through the shared
// TLC-SL interpreter, so runtime enforcement and the model checker use identical
// semantics. Regenerate with: node tlc-sl/src/compile.mjs <spec> --target js
import { decide } from '../../src/interp.mjs';

export const model = ${json};

/**
 * evaluate(action) -> decision
 *   action.type           operation name
 *   action.<var> | env    variable values (state + inputs); missing state defaults to init
 * returns { applies, allowed?, level?, reason?, invariant }
 */
export function evaluate(action) {
  return decide(model, action);
}

export default { id: model.id, level: model.level, title: model.title, model, evaluate };
`;
}
