/**
 * tlc-sl/src/targets/tla.mjs
 * TLA+ export target.
 *
 * Emits a TLA+ module + .cfg for the TLC model checker. This lets the SAME
 * invariant be checked by an industrial, externally-audited tool.
 *
 * HONEST STATUS: this is an emitter. The output is committed but has NOT been run
 * through TLC in this build (TLC needs a Java runtime + tla2tools.jar, absent from
 * the build environment). The in-process checker (checker.mjs) IS run and is the
 * verified path. Treat the .tla output as truth_status: unverified until a TLC run
 * is recorded in evidence.
 */

function tlaName(id) {
  return id.replace(/[^A-Za-z0-9_]/g, '_');
}

function tlaValue(v) {
  if (v === true) return 'TRUE';
  if (v === false) return 'FALSE';
  return `"${v}"`;
}

function renderExpr(node) {
  switch (node.t) {
    case 'lit': return tlaValue(node.value);
    case 'var': return node.name;
    case 'eq': return `(${renderExpr(node.l)} ${node.op === '=' ? '=' : '#'} ${renderExpr(node.r)})`;
    case 'not': return `(~${renderExpr(node.e)})`;
    case 'and': return `(${renderExpr(node.l)} /\\ ${renderExpr(node.r)})`;
    case 'or': return `(${renderExpr(node.l)} \\/ ${renderExpr(node.r)})`;
    case 'implies': return `(${renderExpr(node.l)} => ${renderExpr(node.r)})`;
    case 'ite': return `(IF ${renderExpr(node.c)} THEN ${renderExpr(node.a)} ELSE ${renderExpr(node.b)})`;
    default: throw new Error(`cannot render node '${node.t}' to TLA+`);
  }
}

export function emitTLA(model) {
  const name = tlaName(model.id);
  const vars = model.stateVars;
  const varsTuple = `<< ${vars.join(', ')} >>`;

  const typeInvariant = vars
    .map((v) => `  /\\ ${v} \\in { ${model.domains[v].map(tlaValue).join(', ')} }`)
    .join('\n');

  const init = vars
    .map((v) => `  /\\ ${v} = ${tlaValue(model.initState[v])}`)
    .join('\n');

  const opDefs = model.ops.map((op) => {
    const assigned = new Set(op.effects.map((e) => e.var));
    const unchanged = vars.filter((v) => !assigned.has(v));

    const lines = [];
    lines.push(`  /\\ ${renderExpr(op.guard)}`);
    for (const ef of op.effects) lines.push(`  /\\ ${ef.var}' = ${renderExpr(ef.expr)}`);
    if (unchanged.length === vars.length) {
      lines.push(`  /\\ UNCHANGED ${varsTuple}`);
    } else if (unchanged.length > 0) {
      lines.push(`  /\\ UNCHANGED << ${unchanged.join(', ')} >>`);
    }

    let body = lines.join('\n');
    // Existentially quantify per-action inputs.
    if (model.inputVars.length > 0) {
      const binders = model.inputVars
        .map((iv) => `${iv} \\in { ${model.domains[iv].map(tlaValue).join(', ')} }`)
        .join(', ');
      body = `  \\E ${binders} :\n` + lines.map((l) => '  ' + l).join('\n');
    }
    return `Op_${op.name} ==\n${body}`;
  }).join('\n\n');

  const nextDisjuncts = model.ops.map((op) => `  \\/ Op_${op.name}`).join('\n');

  return `---------------------------- MODULE ${name} ----------------------------
\\* GENERATED by the TLC-SL compiler from ${model.id} — ${model.title}.
\\* Article ${model.article}. Enforcement ${model.level}.
\\* STATUS: emitted, NOT yet checked by TLC in this build. See tla.mjs header.
EXTENDS TLC

VARIABLES ${vars.join(', ')}
vars == ${varsTuple}

TypeOK ==
${typeInvariant}

Init ==
${init}

${opDefs}

Next ==
${nextDisjuncts}

Spec == Init /\\ [][Next]_vars

\\* Safety property (Constitution ${model.article}):
Safety == ${renderExpr(model.safety)}
=============================================================================
`;
}

export function emitCfg(model) {
  const name = tlaName(model.id);
  return `\\* GENERATED by the TLC-SL compiler for ${model.id}.
\\* Run: java -jar tla2tools.jar -config ${name}.cfg ${name}.tla
SPECIFICATION Spec
INVARIANT TypeOK
INVARIANT Safety
`;
}
