#!/usr/bin/env node
/**
 * tlc-sl/src/conformance.mjs
 * Generates the conformance report from ACTUAL checker runs (not hand-written).
 *
 * The report maps, for every invariant:
 *   constitution article  ->  TLC-SL spec source  ->  runtime ops enforced
 *                         ->  in-process model-check result  ->  TLA+ export status
 *
 * This directly answers the open item in the constitution's own V&T statement:
 * "whether the Article VIII invariants as written are exactly the invariants
 * implemented in the Policy Engine requires a code-to-spec verification pass."
 *
 * Output: tlc-sl/conformance/report.md and report.json.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { basename, join, resolve, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compilePath, TLC_SL_ROOT } from './compile.mjs';
import { check, necessity } from './checker.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(TLC_SL_ROOT, '..');

export function buildConformance(specPath = join(TLC_SL_ROOT, 'spec')) {
  const compiled = compilePath(specPath);
  const rows = compiled.map(({ model, file }) => {
    const safety = check(model);
    const guards = necessity(model).filter((g) => g.guarded);
    return {
      id: model.id,
      title: model.title,
      article: model.article,
      level: model.level,
      spec: relative(REPO_ROOT, file),
      ops: model.ops.map((o) => o.name),
      safety_ok: safety.ok,
      states_explored: safety.statesExplored ?? null,
      guards_total: guards.length,
      guards_necessary: guards.filter((g) => g.necessary).length,
      tla_export: `tlc-sl/generated/tla/${model.id.replace(/[^A-Za-z0-9_]/g, '_')}.tla`,
      tla_checked_by_tlc: false,
    };
  });
  return rows;
}

export function renderMarkdown(rows) {
  const allOk = rows.every((r) => r.safety_ok);
  const lines = [];
  lines.push('# TLC-SL Conformance Report');
  lines.push('');
  lines.push('GENERATED by `node tlc-sl/src/conformance.mjs` from live checker runs. Do not edit by hand.');
  lines.push('');
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push(`Result: ${rows.filter((r) => r.safety_ok).length}/${rows.length} invariants verified by the in-process exhaustive checker.`);
  lines.push('');
  lines.push('Each row traces one constitutional invariant from its written Article, through its');
  lines.push('TLC-SL source, to the runtime operations it gates, to its machine-checked result.');
  lines.push('');
  lines.push('| Invariant | Article | Spec source | Runtime ops enforced | In-process check | Guards necessary | TLA+ export |');
  lines.push('|---|---|---|---|---|---|---|');
  for (const r of rows) {
    const checkCell = r.safety_ok
      ? `PASS — safety holds over ${r.states_explored} states`
      : 'FAIL';
    lines.push(
      `| **${r.id}** ${r.title} | ${r.article} | \`${r.spec}\` | ${r.ops.join(', ')} | ${checkCell} | ${r.guards_necessary}/${r.guards_total} | emitted, not TLC-run |`
    );
  }
  lines.push('');
  lines.push('## Honest status of each verification path');
  lines.push('');
  lines.push('- **In-process exhaustive check** — RUN in this build. Exhaustive over each model\'s');
  lines.push('  finite reachable state space. This is the verified path.');
  lines.push('- **Guards necessary** — for each guarded operation, removing the guard reachably');
  lines.push('  breaks safety (a mutation/necessity check). A ratio below total means some guard is');
  lines.push('  not load-bearing for that specific safety property; this is reported honestly, not hidden.');
  lines.push('- **TLA+ export** — EMITTED but NOT run through the TLC model checker in this build');
  lines.push('  (TLC needs a Java runtime + `tla2tools.jar`, absent here). Treat `.tla` output as');
  lines.push('  `unverified` until a TLC run is recorded in `evidence/TLC-SL/`.');
  lines.push('- **Lean 4** — not implemented in v0.1.');
  lines.push('');
  lines.push(allOk
    ? 'All shipped invariants hold under their declared guards.'
    : 'One or more invariants FAILED — see rows above. This report blocks promotion.');
  lines.push('');
  return lines.join('\n');
}

function main() {
  const rows = buildConformance();
  const outDir = join(TLC_SL_ROOT, 'conformance');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'report.json'), JSON.stringify({ generated: new Date().toISOString(), rows }, null, 2) + '\n');
  writeFileSync(join(outDir, 'report.md'), renderMarkdown(rows));
  const ok = rows.filter((r) => r.safety_ok).length;
  console.log(`Conformance report written: ${ok}/${rows.length} invariants verified.`);
  process.exit(ok === rows.length ? 0 : 1);
}

if (resolve(process.argv[1] || '') === resolve(fileURLToPath(import.meta.url))) {
  main();
}
